---
- hosts: webservers
  vars:
    app_name: PleaseDeployMe 
    repo_url: https://github.rackspace.com/deni0109/deployolo.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /deployed  #Is this what I want?
    virtualenv_root: /deployed/mac
  tasks:
    - name: git pull project
      git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version=master
      notify:
        - restart app
    - pip: requirements={{webapps_dir}}/{{app_name}}/requirements.txt virtualenv=latest_v3 executable={{virtualenv_root}}/bin/pip3
    - shell: "{{virtualenv_root}}/bin/python3 manage.py deploy"
      args:
        chdir: "{{webapps_dir}}/{{app_name}}"
  handlers:
    - name: restart app
      supervisorctl: name={{app_name}} state=restarted